### ISSUE TITLE
[core-kit] Review `dirlisting-1` generator to support selector and matcher

### ISSUE THREAD

**Issue by geaaru** [macaroni-os/mark-issues#140]
Could be good to improve the `dirlisting-1` generator with selectors.

**Comment by geaaru** [comment]
The new `mark-devkit autogen`/`mark-devkit autogen-thin` now supports *exclude* attribute to skip develop tarballs through the Golang Regex engine.
Here an example:
```yaml
- apache:
        category: www-servers
        dir:
          url: https://archive.apache.org/dist/httpd/
          # NOTE: the native Golang regex engine doesn't support the negative Perl annotations.
          #       We need to investigate on github.com/h2so5/goback project.
          matcher: "httpd-.*.tar.bz2$"
          exclude: "-deps|-alpha|-beta"
        transform:
          - kind: string
            match: 'httpd-'
            replace: ''
          - kind: string
            match: '.tar.bz2'
            replace: ''
        assets:
          - name: "httpd-{{ .Values.version }}.tar.bz2"
 ```
