### ISSUE TITLE
[dev-kit] app-misc/yq-go has wrong RDEPEND

### ISSUE THREAD

**Issue by geaaru** [macaroni-os/mark-issues#255]
```yaml
description: yq is a portable command-line YAML, JSON and XML processor
uri:
- https://github.com/mikefarah/yq
license: Apache-2.0 Boost-1.0 BSD BSD-2 CC0-1.0 ISC LGPL-3+ MIT Apache-2.0 Unlicense
  ZLIB
labels:
  BDEPEND: '>=dev-lang/go-1.16.14 >=dev-lang/go-1.12 app-arch/unzip'
  RDEPEND: '>=dev-vcs/git-1.7.3'
  emerge.packages: app-misc/yq-go
  kit: dev-kit
```

It doesn't make sense to have RDEPEND with git! :scream: 
`yq` is a golang tool without runtime dependencies.
